# Generated by Django 5.2.6 on 2025-09-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetarium', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='showsession',
            options={'ordering': ['-show_time']},
        ),
        migrations.AddField(
            model_name='astronomyshow',
            name='themes',
            field=models.ManyToManyField(related_name='shows', to='planetarium.showtheme'),
        ),
    ]
